### ISSUE TITLE
Can hamster-tools website use BGR instead of RGB?

### ISSUE THREAD

**Issue by sci-42ver** [lost-melody/Lost-Melody.github.io#3]
Currently in Hamster, the schema [uses BGR](https://ihsiao.com/apps/hamster/docs/ColorSchema.html) while the website uses RGB.

Could you make some tweaks for the website code to use BGR, then it will be more convenient to use?

**Comment by lost-melody** [comment]
Added a button to switch between `RGBA` and `ABGR`. Thank you.
