### ISSUE TITLE
中英切換時，不可更替大小寫

### ISSUE THREAD

**Issue by JovianChau** [lost-melody/Lost-Melody.github.io#4]
我在倉想要在輸入中文時，鍵盤按鍵爲大寫，切換英文時爲小寫。
可惜這個效果只有默認的26鍵盤支持，在這個工具自定義的鍵盤不能實現這個效果，希望能加入支持！

**Comment by pengfei0707** [comment]
没办法了，似乎作者大人因为仓输入法加入内置自定义布局后就不再做更新了

**Comment by lost-melody** [comment]
鍵面字母大小寫變化的行爲不受此網頁版編輯器控制，因爲倉輸入法的佈局系統並未提供調整選項。
目前看來，若按鍵的「標籤 (label)」留空，則顯示「行爲 (action)」的默認文本，卽會隨 `ascii_mode` 開關狀態而變化；若手動調整了標籤文本，則文本固定，不再隨 `ascii_mode` 開關狀態更新。
