### ISSUE TITLE
使用您的工具自己制作了一个双键布局，导入后无法正常使用

### ISSUE THREAD

**Issue by pengfei0707** [lost-melody/Lost-Melody.github.io#5]
打字的时候双键似乎只能被识别到一个字母，基本无法正常使用。希望您不辞辛苦给我这个rime新手一点帮助

**Comment by lost-melody** [comment]
`Rime` 中的雙鍵方案本就是通過字母拼寫運算實現的, 鍵盤 (前端) 向 Rime 引擎輸入的按鍵只能是單個按鍵, 不允許二義.
已知的實現雙鍵的方法, 需要對方案進行修改, 將全鍵盤的編碼映射到雙鍵的若幹按鍵上.
例如, 對於雙鍵`[QW]`, 需要在鍵盤上設置輸入值 (一般取首字 `q`), 隨後在方案拼寫中將帶有 `[qw]` 的編碼改寫爲選定的字母 `q`: `xform/[qw]/q/`.
顯而易見的問題是, 這種方式實現的雙鍵無法在打字過程中選擇編碼.
